apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-flow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nimbus-flow
  template:
    metadata:
      labels:
        app: nimbus-flow
    spec:
      containers:
        - name: nimbus-flow
          image: public.ecr.aws/v6m8y3a9/nimbus-flow:v0.1.2
          resources:
            requests:
              cpu: 0.5
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 3000

